import type { FinalizedRecord } from '../types';

function isoDaysAgo(days: number): string {
  const d = new Date();
  d.setHours(12, 0, 0, 0);
  d.setDate(d.getDate() - days);
  return d.toISOString();
}

/**
 * 无真实定稿数据时用于铺满栅格，便于对齐即梦式布局验收（不入库、不持久化）。
 */
export const LIBRARY_DEMO_RECORDS: FinalizedRecord[] = [
  {
    materialId: 'demo-lib-01',
    assetId: 'da1',
    imageUrl: '',
    taskId: 'demo',
    taskName: '冬季上新',
    createdAt: isoDaysAgo(0),
    market: '国内',
    topic: '服饰',
    finalPrompt: '（演示）极简棚拍大衣，暖色侧光',
    visualDna: '（演示）',
    deliveryStatus: '投放中',
    ctr: 0.071,
    ingest: {
      at: isoDaysAgo(0),
      workflowRunId: 'wf-demo-1001',
      requestId: 'req-demo-1001',
      operator: '演示账号',
    },
    business: { starred: true, tags: ['主推', '冬'] },
  },
  {
    materialId: 'demo-lib-02',
    assetId: 'da2',
    imageUrl: '',
    taskId: 'demo',
    taskName: '冬季上新',
    createdAt: isoDaysAgo(0),
    market: '东南亚',
    topic: '3C',
    finalPrompt: '（演示）耳机场景图，桌面静物',
    visualDna: '（演示）',
    deliveryStatus: '未投放',
    ctr: 0.028,
    ingest: {
      at: isoDaysAgo(0),
      workflowRunId: 'wf-demo-1002',
      requestId: 'req-demo-1002',
      operator: '演示账号',
    },
  },
  {
    materialId: 'demo-lib-03',
    assetId: 'da3',
    imageUrl: '',
    taskId: 'demo',
    taskName: '圣诞活动',
    createdAt: isoDaysAgo(1),
    market: '欧美',
    topic: '礼品',
    finalPrompt: '（演示）礼盒与丝带，节日氛围',
    visualDna: '（演示）',
    deliveryStatus: '测试中',
    ctr: 0.05,
    ingest: {
      at: isoDaysAgo(1),
      workflowRunId: 'wf-demo-1003',
      requestId: 'req-demo-1003',
      operator: '演示账号',
    },
    business: { markAsHigh: true },
  },
  {
    materialId: 'demo-lib-04',
    assetId: 'da4',
    imageUrl: '',
    taskId: 'demo',
    taskName: '圣诞活动',
    createdAt: isoDaysAgo(1),
    market: '国内',
    topic: '美妆',
    finalPrompt: '（演示）唇釉微距，柔和渐变背景',
    visualDna: '（演示）',
    deliveryStatus: '未投放',
    ingest: {
      at: isoDaysAgo(1),
      workflowRunId: 'wf-demo-1004',
      requestId: 'req-demo-1004',
      operator: '演示账号',
    },
    business: { starred: true, markAsHigh: true },
  },
  {
    materialId: 'demo-lib-05',
    assetId: 'da5',
    imageUrl: '',
    taskId: 'demo',
    taskName: '拉新素材',
    createdAt: isoDaysAgo(2),
    market: '国内',
    topic: '食品',
    finalPrompt: '（演示）零食包装平铺，高饱和',
    visualDna: '（演示）',
    deliveryStatus: '已结束',
    ctr: 0.033,
    ingest: {
      at: isoDaysAgo(2),
      workflowRunId: 'wf-demo-1005',
      requestId: 'req-demo-1005',
      operator: '演示账号',
    },
  },
  {
    materialId: 'demo-lib-06',
    assetId: 'da6',
    imageUrl: '',
    taskId: 'demo',
    taskName: '拉新素材',
    createdAt: isoDaysAgo(2),
    market: '国内',
    topic: '家居',
    finalPrompt: '（演示）台灯与书桌一角，夜景',
    visualDna: '（演示）',
    deliveryStatus: '未投放',
    ctr: 0.012,
    ingest: {
      at: isoDaysAgo(2),
      workflowRunId: 'wf-demo-1006',
      requestId: 'req-demo-1006',
      operator: '演示账号',
    },
  },
  {
    materialId: 'demo-lib-07',
    assetId: 'da7',
    imageUrl: '',
    taskId: 'demo',
    taskName: '品牌周',
    createdAt: isoDaysAgo(3),
    market: '欧美',
    topic: '运动',
    finalPrompt: '（演示）跑鞋侧面，跑道虚化',
    visualDna: '（演示）',
    deliveryStatus: '投放中',
    ctr: 0.089,
    ingest: {
      at: isoDaysAgo(3),
      workflowRunId: 'wf-demo-1007',
      requestId: 'req-demo-1007',
      operator: '演示账号',
    },
    business: { starred: true },
  },
  {
    materialId: 'demo-lib-08',
    assetId: 'da8',
    imageUrl: '',
    taskId: 'demo',
    taskName: '品牌周',
    createdAt: isoDaysAgo(3),
    market: '东南亚',
    topic: '母婴',
    finalPrompt: '（演示）婴儿用品柔和场景',
    visualDna: '（演示）',
    deliveryStatus: '未投放',
    ingest: {
      at: isoDaysAgo(3),
      workflowRunId: 'wf-demo-1008',
      requestId: 'req-demo-1008',
      operator: '演示账号',
    },
  },
];

export function isLibraryDemoAsset(materialId: string): boolean {
  return materialId.startsWith('demo-lib-');
}
